stephenmcd/filebrowser-safe

filebrowser_safe/settings.py

- SELECT_FORMATS
- EXTENSIONS
For one thing it would be nice to not have to copy all these defaults into my own project. More importantly, Mezzanine depends on at least the `Image` format existing:
- [GalleryImage model](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/galleries/models.py#L120)
- [BlogPost model](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/blog/models.py#L29)

Merge settings with defaults rather than replacing

---

filebrowser_safe/settings.py

- mp4 is primarily a video format. It's what youtube uses.
- add docx

Improve default EXTENSIONS.

---

filebrowser_safe/views.py

I was running into an issue using Amazon S3. One folder was fine (no comparison being done), but when I had two folders, or a folder and a file, the comparison failed and the page crashed. I noticed that for folders, the file objects being pulled from S3 has date=None and filesize=None. This code will handle that situation.

Handle sorting when date or filesize is None (happens for folders in S3)

---

filebrowser_safe/base.py
filebrowser_safe/fields.py
filebrowser_safe/functions.py

See the docs on
[FileField and FieldFile](https://docs.djangoproject.com/en/1.9/ref/models/fields/#filefield-and-fieldfile):
> When you access a FileField on a model, you are given an instance of
> FieldFile as a proxy for accessing the underlying file.
Implementation Details
----------------------
- Use the same descriptor mechanism upstream `FileField` uses to return
a specific class of object rather than the `from_db_value`/`to_python`
methods. These won't work because `FieldFile` needs to be instantiated
with a model instance, which these methods do not have access to.
- Break most of `FileObject` out into `FileObjectMixin` so it can be
subclassed. We need a separate class for compatibility with
`FieldFile` because each one has a `property` with no setter that the
other implements as …

Make FileBrowseField return a FieldFile. Fix #69.

---

filebrowser_safe/fields.py

When I go to edit a FileBrowseField on an existing model, this error
message is flashed and it goes to the root media directory rather than
whatever directory the file is in.
The reason for this is that this code replaces the directory with an
absolute path. I have no idea why. The fb_browse view clearly expects a
relative path:
abs_path = os.path.join(get_directory(), path)

Fix "The requested Folder does not exist" message.

---

filebrowser_safe/functions.py

When models are imported as a side-effect of importing a field used in Mezzanine's EXTRA_MODEL_FIELDS, migrations breaks. Fortunately the import of Site in this file wasn't actually used so we can just drop it.
See https://github.com/stephenmcd/mezzanine/issues/1513

Remove unused imports

---

filebrowser_safe/fields.py
filebrowser_safe/functions.py
filebrowser_safe/settings.py
filebrowser_safe/templates/filebrowser/include/tableheader.html
filebrowser_safe/views.py

Note that the DEBUG change does change behavior -- the debug column now shows up in filebrowser when `DEBUG == True`. I think this is fine but you may disagree.
There may be more settings that can be eliminated but these looked like the easiest targets. I'm thinking converting the remainder to registered mezzanine settings would make it easier to add them to merge them into the mezzanine configuration docs.

Prune Settings

---

filebrowser_safe/settings.py

This setting will now do nothing if not explicitly set. See
https://groups.google.com/forum/#!topic/mezzanine-users/M3JYu-zE87g.

Better FILEBROWSER_MAX_UPLOAD_SIZE default.

---

filebrowser_safe/static/filebrowser/css/filebrowser.css
filebrowser_safe/static/filebrowser/js/upload.js
filebrowser_safe/templates/filebrowser/upload.html

Fix for issue #89: HTML 5 uploader doesn't allow multiple selection of
files
- Changed file selection dialog to a multiple-select enabled dialog
- Updated the processing after file selection to add a row for each
selected file, each with a Remove button to remove that file from the queue
- There is now a single Browse button, rather than one on each row. It can be clicked multiple times to keep adding more files to the queue.
- As before, files are not actually uploaded until Upload button is pressed.
Tested on 
OSX 10.11.6:
- FireFox 49.0
- Chrome 53.0
- Safari 9.1.2
Windows 7
- IE 11
Sneak peek:

Allow multiple file selection when uploading

---

filebrowser_safe/templates/filebrowser/include/filelisting.html

It doesn't appear that the view that the `/browse` view includes the
`MEDIA_URL` at the top level namespace. See
<https://groups.google.com/forum/?_escaped_fragment_=topic/mezzanine-users/drIVDzMXWa4#!topic/mezzanine-users/drIVDzMXWa4>.

MEDIA_URL -> settings_var.MEDIA_URL

---

filebrowser_safe/settings.py

Theses lines have been around since the initial import and I suspect
refer to a dependency or module which no longer exists.

Remove tinymce import. Resolve #96.

---

filebrowser_safe/views.py

Currently, the **"New Name"** form field is empty when trying to rename a file. It would be helpful to have the value set to the old filename.

Show the old filename in file rename form

---

filebrowser_safe/storage.py

This should fix the issue described in https://github.com/stephenmcd/filebrowser-safe/issues/104
This is caused by mismatch of boto version. Django-storages has been updated to use boto3, while filebrowser-safe _assumes_ that the `self.bucket` was created using boto2. The method s3.bucket.list exists only in boto2. 
The fix is to use listdir in **_S3Boto3Storage_**, which in turn is using `self.bucket.objects.filter(Prefix=self._encode_name(name))` to list the content of the bucket
Reference for methods supported in boto3
http://boto3.readthedocs.io/en/latest/reference/services/s3.html?highlight=s3#bucket
Reference for methods supported in boto2
http://boto.cloudhackers.com/en/latest/ref/s3.html#module-boto.s3.bucket

Fixed issue with s3.Bucket object does not support method 'list' any longer

---

filebrowser_safe/views.py

Importing from the `django.core.urlresolvers` module was deprecated in favor of `django.urls` in Django 1.10, and the former was removed entirely in Django 2.0. Import from `django.urls` instead.

Fix import from deprecated `urlresolvers` module

---

filebrowser_safe/base.py

The non-timezone-aware storage API was deprecated in Django 1.10, and removed in Django 2.0. Use the new timezone-aware API instead.

Use timezone-aware storage API

---

README.rst

Update the project repo URL for `django-filebrowser` in the `README`

New url for django-filebrowser repo

---

filebrowser_safe/storage.py

This fixes an issue in `S3BotoStorageMixin` where the `move` method would fail to preserve the existing files ACL policy. This is problematic for S3 buckets that do not default to `public-read` as objects will default to the buckets ACL policy and _not_ the existing objects policy which is expected for a "move" operation.
1. Create a bucket that doesn't have `public-read` as the buckets default policy
2. Upload a new file
3. Verify correct permissions (as expected)
4. Rename the file
5. Note that the thumbnail is correct, but the image now gets the S3 Access Denied message

Preserve ACL when when we 'move' a file on S3.

---

filebrowser_safe/storage.py

The listdir function returns two values, one for directory names and one
for file names. These are lists of strings and thus do not have a delete
method. Instead of trying to delete each array, we loop through them to
build keys that we can delete.

Fix rmtree method of S3BotoStorageMixin

---

.gitignore
filebrowser_safe/locale/cs/LC_MESSAGES/django.po
filebrowser_safe/storage.py

The reason of this PR, is that I was encountering problems using the `mixin` to upload images to Google Cloud Storage from a RichText source. It looks like the bucket changed in GCS and doesn't support the method `list()`, so I used `listdir` in the same way that it's done for the S3 mixin. 
The `_clean_name` method was nowhere to be found, so I just replicate its behaviour to make it work.
- Fixes `_clean_name` method, which didn't exist anymore in `storages.backends.gcloud.GoogleCloudStorage`
- Fixes issue with method `list()` in Bucket, since that's not supported any longer. Use of `listdir` instead.
- Add `.idea` to `.gitignore`
**Tested using:**
- Mezzanine==4.3.1                          
- django-storages[google]==1.7.1
- google-cloud-storage==1.14.0

Fix issues with old methods in GoogleStorageMixin

---

.travis.yml
filebrowser_safe/base.py
filebrowser_safe/fields.py
filebrowser_safe/forms.py
filebrowser_safe/static/filebrowser/css/filebrowser.css
filebrowser_safe/views.py
tox.ini

When combined with the [2.2 Compatibility PR for Mezzanine ](https://github.com/stephenmcd/mezzanine/pull/1956) this PR makes filebrowser_safe compatible with Django 2.2

filebowser-safe Django 2.2 compatability

---

.github/workflows/main.yml
filebrowser_safe/base.py
filebrowser_safe/templates/filebrowser/custom_field.html
filebrowser_safe/templates/filebrowser/include/filelisting.html
filebrowser_safe/templates/filebrowser/include/filter.html
filebrowser_safe/templates/filebrowser/include/paginator.html
filebrowser_safe/templates/filebrowser/include/tableheader.html
filebrowser_safe/templates/filebrowser/index.html
filebrowser_safe/templatetags/fb_tags.py
filebrowser_safe/urls.py
filebrowser_safe/views.py
tests/urls.py
tox.ini

Add Django 4.0.0 compatibility.
* Django template tags `ifequal` and `ifnotequal` have been deprecated since 1.2. Change all templates to use `if`
* Django 3.0.0 deprecated urlquote and 4.0.0 removed it. Switch to use urllib.parse.quote()
* Django 3.1 deprecated `url` and 4.0.0 removed it. Switch to use `django.urls.re_path()`
* Drop support for < Django1.5 (its been end of life since September 2, 2014 
* Remove `providing_args` from signal definitions. Its purely documentational and has been removed in Django 4.0.0 
* `smart_text` was deprecated in Django 3.0 and removed in 4.0. Switch to `smart_str`
This should make the package Django 4.0.0 compatible.
According to https://github.com/stephenmcd/filebrowser-safe/blob/master/README.rst#contributing this project follows Mezzanine's …

Django 4.0.0 compatibility, fixes #135
